/* SPDX-License-Identifier: GPL-2.0-only */
/*
 * Copyright (c) 2020, The Linux Foundation. All rights reserved.
 */

#define CONFIG_DRM_MSM 1
#define CONFIG_DRM_MSM_SDE 1
#define CONFIG_SYNC_FILE 1
#define CONFIG_DRM_MSM_DSI 1
#define CONFIG_DRM_MSM_DP 1
#define CONFIG_QCOM_MDSS_DP_PLL 1
#define CONFIG_DRM_SDE_WB 1
#define CONFIG_SDE_RECOVERY_MANAGER 1
#define CONFIG_DRM_MSM_REGISTER_LOGGING 1
#define CONFIG_DRM_SDE_EVTLOG_DEBUG 1
#define CONFIG_QCOM_MDSS_PLL 1
#define CONFIG_MSM_SDE_ROTATOR 0
#define CONFIG_MSM_SDE_ROTATOR_EVTLOG_DEBUG 0
#define CONFIG_DRM_SDE_RSC 1
#define CONFIG_DRM_SDE_ROI_MISR 1
#define CONFIG_DRM_SDE_SHD 1
#define CONFIG_DRM_SDE_SHP 1
#define CONFIG_DRM_MSM_LEASE 1
#define CONFIG_DRM_ANALOGIX_ANX7625 1
